<script setup>
import { computed, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useCartStore } from '../stores/cart'
const route = useRoute(); const router = useRouter(); const cart = useCartStore(); const step = computed(() => route.params.step || 'shipping'); const editing = ref(false); const address = ref(JSON.parse(localStorage.getItem('vora-address') || 'null') || { name: '', line: '', city: '', country: '' }); const draft = ref({ ...address.value }); const payment = ref('card')
function saveAddress () { if (!draft.value.name || !draft.value.line || !draft.value.city || !draft.value.country) return; address.value = { ...draft.value }; localStorage.setItem('vora-address', JSON.stringify(address.value)); editing.value = false }
function editAddress () { draft.value = { ...address.value }; editing.value = true }
function next () { if (step.value === 'shipping') router.push('/checkout/payment'); else if (step.value === 'payment') router.push('/checkout/review'); else { cart.clear(); router.push(`/order-confirmed/VORA-${Date.now().toString().slice(-6)}`) } }
</script>
<template><section class="checkout-shell" dir="rtl"><div class="stepper"><span :class="{ active: step === 'shipping' }">1 الشحن</span><span :class="{ active: step === 'payment' }">2 الدفع</span><span :class="{ active: step === 'review' }">3 المراجعة</span></div><div class="checkout-grid"><div class="checkout-form"><template v-if="step === 'shipping'"><span class="eyebrow">إتمام الطلب / 01</span><h1>عنوان الشحن</h1><div v-if="address.name && !editing" class="address-card"><b>{{ address.name }}</b><p>{{ address.line }}<br>{{ address.city }}, {{ address.country }}</p><button class="text-button" @click="editAddress">تعديل</button></div><form v-if="editing || !address.name" class="address-editor" @submit.prevent="saveAddress"><div class="form-grid"><label>الاسم<input v-model="draft.name" required></label><label>العنوان<input v-model="draft.line" required></label><label>المدينة<input v-model="draft.city" required></label><label>الدولة<input v-model="draft.country" required></label></div><button class="button button-orange" type="submit">حفظ العنوان</button><button v-if="address.name" class="button button-ghost" type="button" @click="editing = false">إلغاء</button></form><button v-else class="button button-ghost" @click="editAddress">+ إضافة عنوان جديد</button></template><template v-else-if="step === 'payment'"><span class="eyebrow">إتمام الطلب / 02</span><h1>طريقة الدفع</h1><label class="payment-option"><input v-model="payment" value="card" type="radio"> بطاقة ائتمان <span>VISA · MC · AMEX</span></label><div class="form-grid"><label>رقم البطاقة<input inputmode="numeric" placeholder="4532 9012 3456 7890"></label><label>اسم حامل البطاقة<input placeholder="الاسم الكامل"></label><label>تاريخ الانتهاء<input placeholder="09 / 28"></label><label>رمز الأمان<input inputmode="numeric" placeholder="842"></label></div><p class="secure">دفع آمن ومشفر</p></template><template v-else><span class="eyebrow">إتمام الطلب / 03</span><h1>مراجعة الطلب</h1><div class="review-card"><h3>عنوان الشحن</h3><p>{{ address.name }}<br>{{ address.line }}<br>{{ address.city }}, {{ address.country }}</p><button class="text-button" @click="router.push('/checkout/shipping')">تعديل</button></div><div class="review-card"><h3>طريقة الدفع</h3><p>بطاقة ائتمان ···· 4242</p><button class="text-button" @click="router.push('/checkout/payment')">تعديل</button></div></template><button v-if="!editing" class="button button-orange" @click="next">{{ step === 'review' ? 'تأكيد الطلب' : 'متابعة' }}</button></div><aside class="summary"><h3>ملخص الطلب</h3><div v-for="item in cart.items" :key="item.id"><span>{{ item.name }} × {{ item.qty }}</span><b>{{ (item.price * item.qty).toLocaleString('ar-EG') }} ج.م</b></div><hr><div><span>المجموع الفرعي</span><b>{{ cart.subtotal.toLocaleString('ar-EG') }} ج.م</b></div><div><span>الشحن</span><span>مجاني</span></div><div class="total"><span>الإجمالي</span><b>{{ cart.total.toLocaleString('ar-EG') }} ج.م</b></div></aside></div></section></template>
